### ISSUE TITLE
Create a FAQ around MyResonance virtual economy

### ISSUE THREAD

**Issue by lauredf** [MyResonance/tickets#23]
Could be interesting to answer questions around virtual economy in a FAQ: 
- how tokens are funded
- how donations are made to charities ...

Please feel free to complete with any question you could have

**Comment by SchalkCloete** [comment]
Here are a few questions and answers I suggest, phased as a cute little conversation.

**So, what exactly does MyResonance do?**
MyResonance is a social platform where communities can support worthwhile causes through healthy and sustainable living. Your aim is to earn "tokens" by completing challenges such as tracking regular exercise with Strava or enjoying vegetarian meals. After you accumulate some tokens, you can donate them to a range of different charities or give them to other community members as "likes." Members can share their activities with optional photos and interact through comments.  

**OK, that's interesting. But how do my donations of tokens benefit the charities?**
Tokens are only created when one of our donors commits to pay for them. The community then decides which charities should receive this donation by completing challenges and distributing their tokens between the different causes. When the targeted number of tokens indicated on any charity on the Causes page is reached, we make the appropriate monetary donation. 

**Wow, so I can support charities without paying anything? That sounds too good to be true!**
Yes, you can! MyResonance and its donors want to recognize the great value you create for society by building and maintaining a healthy and sustainable lifestyle. Society does not properly recognize this value today and we want to change that. 

**Can you explain a bit more about what's in it for donors?**
MyResonance strongly increases the value of donations by using them as motivation for healthy and sustainable living. The money still ends up with good causes (like any other donation), but it also improves the lives of community members along the way. Since a healthy and sustainable lifestyle is worth hundreds of Euros every month, MyResonance helps donors multiply the value of their donations. We're currently refining our estimate of this added value on "this forum". 

**That sounds great! Can I also donate something?**
Sure, any donation is welcome! The more donations we get, the greater the value of each token becomes. Just click on the link directly above the token balance table at the bottom of the Company page to show your interest and we'll be in touch. A more streamlined solution is coming soon. 

**I'm sorry I have to ask this, but how do I know the charities will actually receive the money?**
Fair question. One should be very careful with money on the internet. We keep a record of certificates of all charity donations for this community on the Causes page. A record of all the donations made in the MyResonance universe can be viewed "here".

**Great! I'd like to invite my friends, but they'll want an app...**
We get that. An app is coming soon. In the meantime, please help us iron out any last wrinkles in the user experience by reporting any issues in the chat on the bottom right. You can also make suggestions for improvement on Github "here".

**Comment by SchalkCloete** [comment]
To continue the little conversation above...

**Fair enough. Can you give some best practice guidelines for using MyResonance on my mobile in the meantime?**
Sure thing! Here are some pointers:
- First, create a bookmark to myresonance.io in your phone's default browser so that you always have easy access. 
- Add pictures to your posts using your phone's camera. This is particularly useful for the Recycling and Vegetarian challenges where you need a photo to earn tokens. In either of these challenges, tap on a new post and then on the little picture icon to access your phone's camera. 
- For the Active challenge, always be on the lookout for a beautiful, interesting, or funny picture on your workouts. You'll receive an email after each workout that allows you to conveniently add a picture (with optional description) from your phone's gallery to share with the community. People will often give you more tokens if you post a nice picture!
- Starting the timer for the push-up challenge from your mobile is highly convenient.
- Browse the community feed! MyResonance can be a fun time-filler whenever you have a few idle minutes. Check what other community members were up to, check how your team measures up, and give out a couple of tokens :-)

**OK, I'll give it a go! I was also wondering about the functions of the different buttons beneath and inside each post.**
Yes, that's a very important part of the MyResonance experience. Here are some details:
- The most important button is the MyResonance logo. Tapping or clicking this button gives some of your tokens to the person who made the post. In essence, it's a more authentic version of the "like" button you find on other social media platforms. Tap the button multiple times in quick succession to give more than one token. 
- The next button allows you to write a comment, plain and simple. 
- On your own posts, you'll also find a star button that will display this post on your profile page. Your profile will always show the four most recently starred posts to brighten things up. There's also a promote button you can use to send your most interesting posts to the community home page. 
- When writing a post, you can tag another community member through the @ button to draw their attention. Finding the right member becomes easier when you type the first couple of letters of their name after the @ symbol. This can also be done when writing comments. 
- The # button is mostly used automatically, but if you see you're not earning tokens for your post, you might need to add the action using this button. 
- The picture button allows you to take a photo using your camera or upload one from your gallery as described in the previous question.

**Comment by SchalkCloete** [comment]
Another small continuation based on feedback from one user who through the role of communities should be better clarified. 

**Great! Another question: Is there a solution catering for custom groups like my work team, family/friends, or blog followers?**
Yes! You can create your own community on MyResonance and send the sign-up link only to a select number of people. It is also possible to be part of multiple communities at any given time. "Here we need some good instructions on how to set this up..."

**Comment by SchalkCloete** [comment]
Here is a question to add about Strava-use in the Fitness Challenge. 

**I can't see an option to record activities like yoga or weight training on Strava for the Fitness Challenge. What do I do?**
Yes, this is a bit confusing. If you use the Strava mobile app, activities without GPS tracking cannot be recorded directly. As a workaround, simply record walking (or anything else). When you're done, stop and finish the activity. On the next screen, you can easily correct the type of activity before saving. If you have a fitness watch linked to Strava, you may be able to record non-GPS activities directly.
